#!/usr/bin/env python3
"""
tps-fountain-api-scrape.py
Tulsa Public Schools Fountain scraper (Gen 2)

Fountain (web.fountain.com) is a hiring platform. The public careers page
(https://web.fountain.com/c/tulsa-schools/tulsa-schools/US) is a client-side
rendered SPA — the raw HTML is just a JS bootstrap shell with a
"please enable JavaScript" fallback message, so it can never be parsed
directly with requests + BeautifulSoup.

Instead, the page's own JS calls a public, unauthenticated JSON endpoint to
populate the listing:

    https://web.fountain.com/c/tulsa-schools/tulsa-schools/US.json
    https://web.fountain.com/c/tulsa-schools/tulsa-schools/US.json?page=2
    ...

Confirmed working with a plain HTTP GET — no session/cookies/auth token
required. Each entry gives: title, id (uuid), to_param (URL slug),
location_name (this is a DEPARTMENT name, e.g. "Transportation", NOT a
city — see FRAGILITY NOTE below), location_address (street address string),
location_state_code, job_type (observed null on every sampled record).

FRAGILITY NOTES (flagged per request):
  1. This JSON endpoint is not documented/versioned by Fountain anywhere
     public — it's the same internal endpoint the SPA's JS calls to hydrate
     itself. It could change shape or path on a future Fountain deploy with
     no notice. Treat failures here as "check if the endpoint moved" first.
  2. The Fountain JSON has no posted-date field at all. Instead, date_posted
     is pulled from "Last Revised Date: <Month Day, Year>" inside the linked
     Google Doc/Drive job description document, when present. Not every
     posting has one — for those, date_posted defaults to today's date rather
     than an actual posted date, so it should not be read as reliable
     "recently posted" signal for every listing.
  3. The list endpoint has no job description field. The per-opening detail
     page (https://web.fountain.com/c/tulsa-schools/tulsa-schools/US/<to_param>)
     is ALSO a bare JS shell with no server-rendered fallback (confirmed via
     direct fetch), so getting anything at all requires Selenium to render
     it. The rendered page only has a short blurb + a "Full Job Description:"
     link out to an externally-hosted Google Doc/Drive file (usually a PDF)
     with the real content — that linked doc, not the Fountain page itself,
     is the authoritative description AND is where salary/date come from
     (see resolve_external_description() and the Grade/Last Revised Date
     parsing below). Selenium is only used to render the Fountain page long
     enough to find that link — the actual content extraction happens
     against the linked doc/PDF. The link is searched for anywhere in the
     rendered body (not scoped to a specific container), since the "jss###"
     classname the summary text lives in is auto-generated by react-jss/
     Material-UI based on stylesheet insertion order and is NOT guaranteed
     stable across a future Fountain deploy; that specific div.jss222.jss223
     container, then generic extraction (main/article/[role=main]/body),
     are only used as a last-resort fallback if the link itself can't be
     found or resolved. If the linked doc isn't publicly shared ("anyone
     with the link can view"), the export/download fails gracefully and
     falls back to whatever inline text is available — but then salary and
     date parsing have nothing to work with either, since "Grade:"/"Last
     Revised Date:" only appear in the linked doc, never in the Fountain
     page itself.

     If BOTH the link search and every fallback come up empty on every
     single job (not just some), the detail page likely isn't hydrating any
     real content at all in headless Selenium — the detail page's raw HTML
     includes a Cloudflare challenge-platform script
     (/cdn-cgi/challenge-platform/scripts/jsd/main.js), and Cloudflare's bot
     scoring often flags a datacenter IP (like a production server) much
     more aggressively than a residential browser session. get_job_details()
     now polls for the rendered body text to actually grow (rather than a
     fixed sleep) and logs explicitly if the page looks like a Cloudflare
     interstitial rather than real content, so a "Page appears to be a
     Cloudflare challenge/interstitial" warning in the logs confirms this is
     the cause. If that's confirmed and persists, the practical options are:
     a residential/rotating proxy, a stealth-patched browser driver
     (undetected-chromedriver or similar), or asking TPS/Fountain support
     whether an API key/allowlisting is available — plain Selenium is
     unlikely to get past active bot-management on its own.
  4. No rate limiting was hit while probing this endpoint manually, but it
     was only requested a handful of times. A scheduled scrape should keep
     the existing polite delay between requests (see time.sleep below) and
     back off / alert on repeated 429s rather than retrying aggressively.

location_name is actually the hiring department (e.g. "Transportation",
"Child Nutrition", "Multiple School Sites") rather than a city, so it cannot
be matched against the served-cities table directly. Multiple departments
routinely share one physical building (e.g. "Finance & Payroll" and
"Accounting" both sit at "3027 S New Haven Ave, Tulsa, OK 74114, USA"), so
company sites are matched by address1 (the street-only portion of
location_address — see _street_address()) rather than by department name.
This intentionally bypasses utils.company_operations.get_or_create_company_site(),
which matches by site_name and would otherwise create a separate site per
department at the same address. If no site exists yet at that address, one
is created as a Branch Office. The job's own city_id is resolved separately
by parsing the city out of the full location_address (TPS's whole feed is
Tulsa-area, so this is expected to resolve to Tulsa or a nearby served city
on virtually every record).
"""

from utils.db_connection import get_database_connection, close_connection
from utils.posting_operations import (
    store_job_listing, update_job_listing, load_active_jobs_cache, check_job_in_cache,
    update_job_verified_timestamp, mark_stale_jobs_closed,
)
from utils.company_operations import get_company_config_by_name
from utils.location_utilities import find_served_city, get_city_id
from utils.utility_methods import setup_logging, normalize_job_type, parse_salary_text

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from utils.selenium_config import SeleniumConfig

from datetime import datetime
from urllib.parse import urlparse
import hashlib
import os
import re
import tempfile
import time
import requests
import mammoth
import PyPDF2
from bs4 import BeautifulSoup, NavigableString, Tag
from typing import Dict, List, Optional

logger = setup_logging('Tulsa Public Schools')

COMPANY_NAME = 'Tulsa Public Schools'
SOURCE_JOB_BOARD = 'Tulsa Fountain Scraper'
MAX_PAGES = 50  # safety cap in case pagination metadata ever misbehaves

# Tulsa Public Schools — K-12 district. Matched against job title +
# location_name (the hiring department, e.g. "Transportation", "Facilities").
_FUNCTION_KEYWORDS = {
    'Education/Training': [
        'teacher', 'instructor', 'educator', 'faculty', 'classroom',
        'special education', 'librarian', 'counselor', 'speech', 'tutor',
        'paraprofessional', 'para teacher', 'academic partner', 'iep facilitator',
        'school psychologist', 'teaching and learning', 'dean of students',
        'interpreter', 'coach', 'learning director',
    ],
    'Administration': [
        'principal', 'superintendent', 'director', 'coordinator', 'supervisor',
        'administrative', 'admin', 'secretary', 'clerk',
    ],
    'Information Technology': [
        'technology', 'computer', 'network', 'systems', 'tech support',
        'audio video', 'hris', 'client services',
    ],
    'Transportation/Logistics': [
        'bus', 'driver', 'transportation', 'fleet',
    ],
    'Finance': [
        'business manager', 'finance', 'accounting', 'bookkeeper', 'payroll', 'buyer',
    ],
    'Human Resources': [
        'human resources', 'hr', 'recruiter', 'talent management', 'compensation',
    ],
    'Security': [
        'security', 'safety', 'sro', 'resource officer', 'guard', 'police',
    ],
    'Skilled Labor': [
        'maintenance', 'custodial', 'custodian', 'janitor', 'groundskeeper',
        'facilities', 'hvac', 'carpentry', 'electrician', 'plumb', 'roofer',
        'painter', 'sheet metal', 'mechanic', 'journeyperson', 'craftsperson',
    ],
    'Food Service': [
        'cafeteria', 'cook', 'child nutrition', 'nutrition',
    ],
    'Healthcare Provider': [
        'nurse', 'health assistant', 'occupational therapist',
    ],
    'Customer Service': [
        'family support', 'family specialist', 'parent involvement', 'family retention',
    ],
}


def _map_job_to_function(cursor, job_title: str, location_name: str) -> Optional[int]:
    match_text = f"{job_title or ''} {location_name or ''}".lower()
    for function_name, keywords in _FUNCTION_KEYWORDS.items():
        for keyword in keywords:
            if keyword in match_text:
                cursor.execute("SELECT id FROM functions WHERE name = %s", (function_name,))
                result = cursor.fetchone()
                if result:
                    logger.info(f"  Mapped '{job_title}' to function: {function_name}")
                    return result['id']
    cursor.execute("SELECT id FROM functions WHERE name = %s", ('Other',))
    result = cursor.fetchone()
    if result:
        logger.info(f"  Mapped '{job_title}' to function: Other (no match)")
        return result['id']
    return None


def _parse_city_from_address(address: str, state_code: str) -> Optional[str]:
    """Extract the city from a Fountain location_address string.

    Observed formats:
      "2710 E 11th St, Tulsa, OK 74104, USA"
      "8934 East Latimer Street, Tulsa, OK, 74115, US"
      "Tulsa, OK, US"
    In every case the city is the comma-segment immediately before the one
    starting with the state code.
    """
    if not address or not state_code:
        return None
    parts = [p.strip() for p in address.split(',')]
    for i, part in enumerate(parts):
        if i > 0 and part.upper().startswith(state_code.upper()):
            return parts[i - 1]
    return None


def _street_address(location_address: str) -> Optional[str]:
    """Keep only the street portion of a Fountain location_address string —
    everything after the first comma is city/state/zip, not part of the
    street address (e.g. "3027 S New Haven Ave, Tulsa, OK 74114, USA" ->
    "3027 S New Haven Ave")."""
    if not location_address:
        return None
    street = location_address.split(',')[0].strip()
    return street or None


def _get_or_create_site_by_address(cursor, company_id: int, location_name: str, address1: str,
                                    city_id: Optional[int], state_id: Optional[int],
                                    country_id: Optional[int], logger) -> Optional[int]:
    """Get or create a companysite matched by address1 rather than site_name.

    Fountain's location_name is a department (e.g. "Finance & Payroll",
    "Accounting"), not a site identifier — multiple departments commonly
    share one physical address, and should resolve to the same companysite
    row rather than creating a duplicate per department. This intentionally
    bypasses utils.company_operations.get_or_create_company_site(), which
    matches by site_name and would create a separate row per department.
    """
    if not address1:
        return None

    cursor.execute(
        "SELECT id FROM companysite WHERE company_id = %s AND LOWER(address1) = LOWER(%s)",
        (company_id, address1)
    )
    result = cursor.fetchone()
    if result:
        logger.info(f"  Found existing company site at '{address1}' (ID: {result['id']})")
        return result['id']

    cursor.execute("SELECT id FROM companysitetype WHERE name = %s", ('Branch Office',))
    type_result = cursor.fetchone()
    site_type_id = type_result['id'] if type_result else None

    cursor.execute("""
        INSERT INTO companysite (company_id, site_name, city_id, address1, state_id, country_id, site_type, is_active)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING id
    """, (company_id, location_name.strip() if location_name else None, city_id, address1,
          state_id, country_id, site_type_id, True))
    result = cursor.fetchone()
    site_id = result['id']
    logger.info(f"  Created new company site '{location_name}' at '{address1}' (ID: {site_id})")
    return site_id


_GRADE_SALARY_PATTERN = re.compile(r'Grade:?\s*\S+\s*\(([^)]+)\)', re.IGNORECASE)
_LAST_REVISED_PATTERN = re.compile(
    r'Last Revised Date:?\s*([A-Za-z]+\s+\d{1,2},?\s*\d{4}|[A-Za-z]+\s+\d{4})',
    re.IGNORECASE,
)


def _parse_salary_from_grade(text: str):
    """Parse a line like "Grade: H-5 ($12.37 - $15.69)" into
    (minimum_salary, maximum_salary, pay_frequency). Returns (None, None, None)
    if no Grade line is found. These district pay-grade ranges are hourly
    rates by convention (the "H-" grade prefix), but the source text never
    says "hourly" explicitly, so pay_frequency is asserted rather than
    detected from the text itself.
    """
    match = _GRADE_SALARY_PATTERN.search(text or '')
    if not match:
        return None, None, None
    parsed = parse_salary_text(match.group(1))
    if parsed['minimum_salary'] is None:
        return None, None, None
    return parsed['minimum_salary'], parsed['maximum_salary'], 'hourly'


def _parse_last_revised_date(text: str) -> Optional[datetime]:
    """Parse "Last Revised Date: June 18, 2025" (day+month+year) or
    "Last Revised Date: June 2025" (month+year only — assumes the 1st)."""
    match = _LAST_REVISED_PATTERN.search(text or '')
    if not match:
        return None
    date_str = match.group(1).strip()
    for fmt in ('%B %d, %Y', '%B %d %Y'):
        try:
            return datetime.strptime(date_str, fmt)
        except ValueError:
            continue
    try:
        return datetime.strptime(date_str, '%B %Y')  # month+year only -> day 1
    except ValueError:
        logger.warning(f"  Could not parse Last Revised Date: '{date_str}'")
        return None


def _find_full_description_link(container: Tag) -> Optional[str]:
    """Find the <a> tag immediately following the phrase "Full Job
    Description:" within a rendered description container."""
    found_phrase = False
    for node in container.descendants:
        if isinstance(node, NavigableString):
            if 'full job description' in node.lower():
                found_phrase = True
        elif isinstance(node, Tag) and node.name == 'a' and found_phrase:
            href = node.get('href')
            if href:
                return href
    return None


def _extract_docx_text(file_path: str) -> str:
    try:
        with open(file_path, 'rb') as docx_file:
            result = mammoth.extract_raw_text(docx_file)
            return result.value
    except Exception as e:
        logger.warning(f"  Failed to extract DOCX text: {e}")
        return ""


def _extract_pdf_text(file_path: str) -> str:
    try:
        text = ""
        with open(file_path, 'rb') as pdf_file:
            pdf_reader = PyPDF2.PdfReader(pdf_file)
            for page in pdf_reader.pages:
                text += page.extract_text() + "\n"
        return text
    except Exception as e:
        logger.warning(f"  Failed to extract PDF text: {e}")
        return ""


def _sniff_file_kind(content: bytes) -> Optional[str]:
    """Identify a downloaded Drive file by magic bytes rather than trusting
    Content-Type, which Drive's uc?export=download endpoint often reports
    generically (e.g. application/octet-stream) for both PDFs and DOCX."""
    if content[:5] == b'%PDF-':
        return 'pdf'
    if content[:2] == b'PK':  # DOCX/XLSX/etc. are zip containers
        return 'docx'
    return None


def resolve_external_description(session: requests.Session, url: str) -> Optional[str]:
    """Resolve the "Full Job Description:" link to its text content.

    Handles a native Google Doc (exported as plain text) or a Google
    Drive-hosted file (downloaded and run through mammoth/PyPDF2 depending on
    content type, same as applitrack's DocumentProcessor). Returns None on
    any failure — most commonly because the doc/file isn't shared publicly
    ("anyone with the link can view"), which the caller should treat as
    "fall back to the inline rendered text" rather than a hard error.
    """
    try:
        doc_match = re.search(r'/document/d/([a-zA-Z0-9_-]+)', url)
        if doc_match:
            export_url = f"https://docs.google.com/document/d/{doc_match.group(1)}/export?format=txt"
            response = session.get(export_url, timeout=20)
            response.raise_for_status()
            text = response.text.strip()
            if text and len(text) > 100 and '<html' not in text.lower()[:200]:
                logger.info(f"  Extracted {len(text)} characters from linked Google Doc")
                return text
            logger.warning("  Google Doc export returned no usable text (likely not shared publicly)")
            return None

        file_match = re.search(r'/file/d/([a-zA-Z0-9_-]+)', url) or re.search(r'[?&]id=([a-zA-Z0-9_-]+)', url)
        if file_match:
            download_url = f"https://drive.google.com/uc?export=download&id={file_match.group(1)}"
            response = session.get(download_url, timeout=30)
            response.raise_for_status()
            content_type = response.headers.get('Content-Type', '').lower()
            # Drive's download endpoint often reports a generic Content-Type
            # for both PDFs and DOCX, so sniff the actual file signature
            # first rather than guessing an extraction order and logging a
            # spurious "Failed to extract" warning when the guess is wrong.
            file_kind = _sniff_file_kind(response.content)

            with tempfile.NamedTemporaryFile(delete=False) as temp_file:
                temp_file.write(response.content)
                temp_path = temp_file.name
            try:
                if file_kind == 'pdf' or 'pdf' in content_type:
                    text = _extract_pdf_text(temp_path)
                elif file_kind == 'docx' or 'word' in content_type or 'officedocument' in content_type:
                    text = _extract_docx_text(temp_path)
                elif 'text/plain' in content_type:
                    text = response.text
                else:
                    logger.warning(f"  Could not identify Drive file type (content-type: '{content_type}'), "
                                    f"trying PDF then DOCX extraction")
                    text = _extract_pdf_text(temp_path) or _extract_docx_text(temp_path)
            finally:
                try:
                    os.unlink(temp_path)
                except Exception:
                    pass

            text = (text or '').strip()
            if len(text) > 100:
                logger.info(f"  Extracted {len(text)} characters from linked Drive file")
                return text
            logger.warning("  Drive file yielded no usable text (likely not public, or an unrecognized format)")
            return None

    except Exception as e:
        logger.warning(f"  Could not resolve external description link '{url}': {e}")
        return None

    logger.warning(f"  Unrecognized Google Docs/Drive URL shape: {url}")
    return None


def _update_company_scrape_completed(cursor, company_id: int):
    cursor.execute("""
        UPDATE company SET last_full_scrape_completed = CURRENT_TIMESTAMP WHERE id = %s
    """, (company_id,))
    logger.info(f"Updated last_full_scrape_completed for company {company_id}")


def _log_scraping_activity(cursor, company_id: int, stats: Dict):
    cursor.execute("""
        INSERT INTO scrapinglog (
            job_board, company_id, jobs_found, jobs_added, jobs_updated,
            jobs_skipped, errors, status
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        SOURCE_JOB_BOARD,
        company_id,
        stats.get('found', 0),
        stats.get('added', 0),
        stats.get('updated', 0),
        stats.get('skipped', 0),
        str(stats.get('errors', [])),
        'completed'
    ))


class SeleniumJobScraper:
    """Renders Fountain's JS-only detail pages just enough to scrape a
    best-effort description. See FRAGILITY NOTE #3 at the top of this file."""

    def __init__(self, headless=True):
        self.driver = None
        self.headless = headless
        self.setup_driver()
        self.doc_session = requests.Session()
        self.doc_session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
        })

    def setup_driver(self):
        try:
            chrome_options = SeleniumConfig.get_chrome_options(headless=self.headless)
            self.driver = webdriver.Chrome(
                service=Service(ChromeDriverManager().install()),
                options=chrome_options
            )
            SeleniumConfig.setup_driver_timeouts(self.driver)
            logger.info("Selenium WebDriver initialized")
        except Exception as e:
            logger.error(f"Failed to initialize WebDriver: {e}")
            raise

    def get_job_details(self, job_url: str, timeout=15) -> Dict:
        """Returns {'description', 'minimum_salary', 'maximum_salary',
        'pay_frequency', 'date_posted'}. The salary/date fields are only ever
        populated when the linked Google Doc/Drive description resolves,
        since "Grade:"/"Last Revised Date:" only appear in that document —
        never in the Fountain page's own inline text."""
        empty = {
            'description': '', 'minimum_salary': None, 'maximum_salary': None,
            'pay_frequency': None, 'date_posted': None,
        }

        logger.info(f"  Loading job detail page: {job_url}")

        try:
            self.driver.get(job_url)
            wait = WebDriverWait(self.driver, timeout)
            try:
                wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
            except TimeoutException:
                logger.warning(f"  Timed out waiting for <body> at {job_url} "
                                f"(landed on: {self.driver.current_url!r})")
                return empty

            # The SPA shell's <body> exists immediately, before React has
            # hydrated any real content — a fixed short sleep isn't a
            # reliable signal that hydration finished. Poll body text length
            # instead, growing the wait window with the SPA's own actual
            # progress rather than guessing a fixed delay.
            try:
                WebDriverWait(self.driver, timeout).until(
                    lambda d: d.execute_script("return document.body.innerText.length") > 200
                )
            except TimeoutException:
                logger.warning(
                    f"  Page body text never grew past 200 chars within timeout for {job_url} "
                    f"(current_url: {self.driver.current_url!r}, title: {self.driver.title!r}) — "
                    f"SPA may not have hydrated (see Cloudflare check below)"
                )

            html = self.driver.page_source
        except Exception as e:
            logger.error(f"  Error loading job page {job_url}: {e}")
            return empty

        try:
            lower_html = html.lower()
            if 'cf-browser-verification' in lower_html or 'checking your browser' in lower_html or \
               ('just a moment' in lower_html and 'cloudflare' in lower_html):
                logger.warning(f"  Page at {job_url} appears to be a Cloudflare challenge/interstitial, "
                                f"not real content — headless Selenium is likely being blocked "
                                f"(see FRAGILITY NOTE #3)")

            soup = BeautifulSoup(html, 'html.parser')
            for tag in soup.find_all(['script', 'style', 'noscript']):
                tag.decompose()

            # Find the "Full Job Description:" link anywhere on the page —
            # not scoped to a specific container, since the surrounding
            # div's "jss###" classname is auto-generated and not guaranteed
            # stable across a future Fountain deploy.
            body_tag = soup.find('body')
            full_desc_link = _find_full_description_link(body_tag) if body_tag else None
            if full_desc_link:
                external_text = resolve_external_description(self.doc_session, full_desc_link)
                if external_text:
                    min_sal, max_sal, pay_freq = _parse_salary_from_grade(external_text)
                    return {
                        'description': external_text[:50000],
                        'minimum_salary': min_sal,
                        'maximum_salary': max_sal,
                        'pay_frequency': pay_freq,
                        'date_posted': _parse_last_revised_date(external_text),
                    }
                logger.warning("  Found 'Full Job Description:' link but couldn't resolve its content")

            # Fall back to the specific container identified on the live
            # site, if present.
            container = soup.select_one('div.jss222.jss223')
            if container:
                text = re.sub(r'\s+', ' ', container.get_text(separator=' ', strip=True)).strip()
                if len(text) > 100:
                    logger.info(f"  Extracted description via div.jss222.jss223: {len(text)} characters")
                    return {**empty, 'description': text[:50000]}

            for selector in ['main', 'article', 'div[role="main"]']:
                content = soup.select_one(selector)
                if content:
                    text = re.sub(r'\s+', ' ', content.get_text(separator=' ', strip=True)).strip()
                    if len(text) > 100:
                        logger.info(f"  Extracted description via '{selector}': {len(text)} characters")
                        return {**empty, 'description': text[:50000]}

            if body_tag:
                for tag in body_tag.find_all(['nav', 'header', 'footer']):
                    tag.decompose()
                text = re.sub(r'\s+', ' ', body_tag.get_text(separator=' ', strip=True)).strip()
                if len(text) > 100:
                    logger.info(f"  Extracted description from body fallback: {len(text)} characters")
                    return {**empty, 'description': text[:50000]}
                logger.warning(f"  Body text only had {len(text)} characters after hydration wait "
                                f"for {job_url} (raw page_source length: {len(html)})")

            logger.warning(f"  No meaningful rendered description found for {job_url}")
            return empty
        except Exception as e:
            logger.warning(f"  Error extracting description: {e}")
            return empty

    def cleanup(self):
        self.doc_session.close()
        if self.driver:
            try:
                self.driver.quit()
                logger.info("WebDriver closed")
            except Exception:
                pass


class FountainClient:
    """Plain HTTP client for Fountain's public JSON listing API."""

    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
            'Accept': 'application/json',
        })

    def get_all_openings(self, jobboard_url: str) -> List[Dict]:
        all_openings = []
        page = 1
        while page <= MAX_PAGES:
            url = f"{jobboard_url}.json" + (f"?page={page}" if page > 1 else "")
            try:
                logger.info(f"Fetching {url}")
                response = self.session.get(url, timeout=20)
                response.raise_for_status()
                data = response.json()
            except Exception as e:
                logger.error(f"Error fetching page {page}: {e}")
                break

            openings = data.get('openings', [])
            all_openings.extend(openings)

            pagination = data.get('pagination', {})
            next_page = pagination.get('next_page')
            total_pages = pagination.get('total_pages', page)
            logger.info(
                f"  Page {page}/{total_pages}: {len(openings)} openings "
                f"(running total {len(all_openings)})"
            )

            if not next_page or next_page <= page or page >= total_pages:
                break
            page = next_page
            time.sleep(0.5)

        return all_openings

    def close(self):
        self.session.close()


class TulsaPublicSchoolsScraper:

    def __init__(self, conn):
        self.conn = conn
        with self.conn.cursor() as cursor:
            self.company_config = get_company_config_by_name(cursor, COMPANY_NAME)
        if not self.company_config:
            raise ValueError(f"Company '{COMPANY_NAME}' not found in database")
        self.company_id = self.company_config['id']
        self.jobboard_url = self.company_config['jobboard'].rstrip('/')

        # The public listing page (self.jobboard_url, used for the .json API)
        # and the actual per-job apply/detail page live under different path
        # shapes on web.fountain.com — confirmed by checking what a real
        # listing click navigates to:
        #   listing: https://web.fountain.com/c/tulsa-schools/tulsa-schools/US
        #   detail:  https://web.fountain.com/apply/tulsa-schools/opening/<to_param>?brand_id=all
        # An earlier version guessed the detail URL was just jobboard_url +
        # "/<to_param>" — that path returns HTTP 200 but isn't a route the
        # SPA's router recognizes as a job detail page, so it rendered no
        # real content at all (0 characters of body text) rather than
        # erroring, which made it hard to diagnose. The company slug is
        # parsed from jobboard_url rather than hardcoded twice.
        path_parts = [p for p in urlparse(self.jobboard_url).path.split('/') if p]
        company_slug = path_parts[1] if len(path_parts) > 1 else 'tulsa-schools'
        self.apply_base_url = f"https://web.fountain.com/apply/{company_slug}/opening"

        self.client = FountainClient()
        self.selenium_scraper = SeleniumJobScraper(headless=True)

    def build_posting_url(self, to_param: str) -> str:
        return f"{self.apply_base_url}/{to_param}?brand_id=all"

    def create_scraping_hash(self, title: str, url: str, description: str) -> str:
        return hashlib.md5(f"{title}{url}{description}".encode('utf-8')).hexdigest()

    def scrape_jobs(self) -> Dict:
        stats = {'found': 0, 'added': 0, 'updated': 0, 'skipped': 0, 'errors': []}

        try:
            with self.conn.cursor() as cursor:
                logger.info("Step 1: Loading active jobs cache...")
                active_jobs_cache = load_active_jobs_cache(cursor, self.company_id)

                cursor.execute("SELECT id FROM cities WHERE city_name = 'Tulsa'")
                result = cursor.fetchone()
                fallback_tulsa_city_id = result['id'] if result else None

                cursor.execute("SELECT id FROM state WHERE name = 'Oklahoma'")
                result = cursor.fetchone()
                oklahoma_state_id = result['id'] if result else None

                cursor.execute("SELECT id FROM country WHERE iso_code_2 = 'US'")
                result = cursor.fetchone()
                us_country_id = result['id'] if result else None

                cursor.execute("SELECT id FROM officelocations WHERE LOWER(name) = LOWER('On-Site')")
                result = cursor.fetchone()
                default_office_location_id = result['id'] if result else None

                logger.info("Step 2: Fetching openings from Fountain...")
                openings = self.client.get_all_openings(self.jobboard_url)
                if not openings:
                    raise Exception("No openings retrieved from Fountain API")
                stats['found'] = len(openings)

                logger.info("Step 3: Processing jobs...")
                for i, opening in enumerate(openings):
                    try:
                        title = opening.get('title', 'Unknown')
                        to_param = opening.get('to_param')
                        location_name = opening.get('location_name') or ''
                        location_address = opening.get('location_address') or ''
                        location_state_code = opening.get('location_state_code') or ''
                        logger.info(f"Processing job {i+1}/{len(openings)}: {title} ({location_name})")

                        if not to_param:
                            logger.warning("  No to_param found, skipping")
                            stats['skipped'] += 1
                            continue

                        posting_url = self.build_posting_url(to_param)

                        parsed_city = _parse_city_from_address(location_address, location_state_code)
                        city_name = find_served_city(parsed_city) if parsed_city else None
                        city_id = get_city_id(cursor, city_name) if city_name else fallback_tulsa_city_id

                        street_address = _street_address(location_address)
                        company_site_id = _get_or_create_site_by_address(
                            cursor, self.company_id, location_name, street_address,
                            city_id=city_id, state_id=oklahoma_state_id,
                            country_id=us_country_id, logger=logger,
                        )

                        existing_job_id = check_job_in_cache(posting_url, active_jobs_cache)
                        if existing_job_id:
                            update_job_verified_timestamp(cursor, existing_job_id)
                            # Re-run the cheap, no-network derived fields even for
                            # jobs we don't re-scrape a description for. Without
                            # this, a job's function/city/site stay frozen at
                            # whatever they were the first time it was ever
                            # inserted — so fixing a keyword mapping later would
                            # never apply retroactively to already-seen jobs.
                            update_job_listing(cursor, existing_job_id, {
                                'function': _map_job_to_function(cursor, title, location_name),
                                'city_id': city_id,
                                'company_site_id': company_site_id,
                            })
                            stats['updated'] += 1
                            continue

                        details = self.selenium_scraper.get_job_details(posting_url)
                        description = details['description']
                        if not description or len(description.strip()) < 100:
                            # Fountain's detail page is JS-only with no reliably
                            # identifiable description container (see FRAGILITY
                            # NOTE #3) — fall back to a synthetic description
                            # rather than dropping the job entirely.
                            logger.warning("  Rendered description too short, using synthetic fallback")
                            description = (
                                f"{title} — {location_name or 'Tulsa Public Schools'}. "
                                f"See full details and apply at {posting_url}."
                            )

                        job_type_id = None
                        raw_job_type = opening.get('job_type')
                        if raw_job_type:
                            canonical = normalize_job_type(raw_job_type)
                            if canonical:
                                cursor.execute("SELECT id FROM jobtype WHERE name = %s", (canonical,))
                                jt_result = cursor.fetchone()
                                job_type_id = jt_result['id'] if jt_result else None

                        job_data = {
                            'job_title': title,
                            'job_description': description,
                            'posting_url': posting_url,
                            'posting_id': opening.get('id'),
                            # date_posted comes from "Last Revised Date:" in the
                            # linked doc, when present (see FRAGILITY NOTE #2) —
                            # Fountain's own API never provides one. When it
                            # can't be determined, default to today.
                            'date_posted': details['date_posted'] or datetime.now(),
                            'minimum_salary': details['minimum_salary'],
                            'maximum_salary': details['maximum_salary'],
                            'pay_frequency': details['pay_frequency'],
                            'scraping_hash': self.create_scraping_hash(title, posting_url, description),
                            'function': _map_job_to_function(cursor, title, location_name),
                            'job_type_id': job_type_id,
                            'city_id': city_id,
                            'company_site_id': company_site_id,
                            'office_location_id': default_office_location_id,
                        }

                        job_id = store_job_listing(cursor, job_data, self.company_id, SOURCE_JOB_BOARD)
                        logger.info(f"  Stored job ID: {job_id} (site: {location_name}, city_id: {city_id})")
                        stats['added'] += 1
                        time.sleep(0.5)

                    except Exception as e:
                        error_msg = f"Error processing '{opening.get('title', 'Unknown')}': {e}"
                        logger.error(error_msg)
                        stats['errors'].append(error_msg)
                        stats['skipped'] += 1

                logger.info("Step 4: Marking stale jobs as closed...")
                mark_stale_jobs_closed(cursor, self.company_id, logger)

                logger.info("Step 5: Updating company scrape completion...")
                _update_company_scrape_completed(cursor, self.company_id)

                logger.info("Step 6: Logging results...")
                _log_scraping_activity(cursor, self.company_id, stats)

        except Exception as e:
            error_msg = f"Scraping failed: {e}"
            logger.error(error_msg)
            stats['errors'].append(error_msg)

        return stats

    def cleanup(self):
        self.client.close()
        self.selenium_scraper.cleanup()


def run_sanity_check(limit: int = 10):
    """Standalone function to fetch and print openings WITHOUT touching the
    database — run this first to sanity check the API response before wiring
    the scraper into a scheduled job.

        python fountain/tps-fountain-api-scrape.py --check
    """
    client = FountainClient()
    try:
        config_url = "https://web.fountain.com/c/tulsa-schools/tulsa-schools/US"
        openings = client.get_all_openings(config_url)
        print(f"\nTotal openings returned: {len(openings)}\n")
        for opening in openings[:limit]:
            address = opening.get('location_address') or ''
            state_code = opening.get('location_state_code') or ''
            city = _parse_city_from_address(address, state_code)
            print(f"- {opening.get('title')}")
            print(f"    department: {opening.get('location_name')}")
            print(f"    address:    {address}")
            print(f"    parsed city: {city}")
            print(f"    url:        https://web.fountain.com/c/tulsa-schools/tulsa-schools/US/{opening.get('to_param')}")
        if len(openings) > limit:
            print(f"\n...and {len(openings) - limit} more.")
    finally:
        client.close()


def main():
    conn = None
    scraper = None
    try:
        conn = get_database_connection()
        scraper = TulsaPublicSchoolsScraper(conn)

        logger.info(f"Starting {COMPANY_NAME} job scraping...")
        results = scraper.scrape_jobs()

        logger.info("=== SCRAPING SUMMARY ===")
        logger.info(f"Jobs found:   {results['found']}")
        logger.info(f"Jobs added:   {results['added']}")
        logger.info(f"Jobs updated: {results['updated']}")
        logger.info(f"Jobs skipped: {results['skipped']}")
        logger.info(f"Errors:       {len(results['errors'])}")

        if results['errors']:
            logger.error("Errors encountered:")
            for error in results['errors']:
                logger.error(f"  - {error}")

    except Exception as e:
        logger.error(f"Script failed: {e}")
        return 1
    finally:
        if scraper:
            scraper.cleanup()
        close_connection(conn)

    return 0


if __name__ == "__main__":
    import sys
    if '--check' in sys.argv:
        run_sanity_check()
        exit(0)
    exit(main())
